---
namespace: subscale
description: Deploy a production ready K3S cluster
name: k3s-ansible
version: 1.0.0
readme: README.md
authors:
  - luksi1
  - adamc-formlogic
tags:
  - kubernetes
  - k3s
repository: https://github.com/subscale/k3s-ansible
dependencies:
  ansible.posix: ">=1.5.2"
  ansible.utils: ">=2.10.1"
  community.general: ">=7.0.0"
  kubernetes.core: ">=2.4.0"

# build_ignore:
#   - .github
#   - '*.tar.gz'
#   - extra_playbooks
#   - inventory
#   - scripts
#   - test-infra
#   - .ansible-lint
#   - .editorconfig
#   - .gitignore
#   - .gitlab-ci
#   - .gitlab-ci.yml
#   - .gitmodules
#   - .markdownlint.yaml
#   - .nojekyll
#   - .pre-commit-config.yaml
#   - .yamllint
#   - Dockerfile
#   - FILES.json
#   - MANIFEST.json
#   - Makefile
#   - Vagrantfile
#   - _config.yml
#   - ansible.cfg
#   - requirements*txt
#   - setup.cfg
#   - setup.py
#   - index.html
#   - reset.yml
#   - cluster.yml
#   - scale.yml
#   - recover-control-plane.yml
#   - remove-node.yml
#   - upgrade-cluster.yml
#   - library
